name: Test
on: [push, pull_request]

jobs:
  Test_Nodejs:
    name: Test Node.js
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        node: [16, 18, 20]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Test
        run: npm test

  Test_Bun:
    name: Test Bun
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        bun: [latest]
        platform: [ubuntu-latest, macos-latest]
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun }}
      - uses: actions/checkout@v3
      - name: Install
        run: |
          bun install -g node-gyp
          bun install
          node-gyp rebuild
      - name: Test
        run: bun run test
